// Cloudflare Workers configuration file
name = "switchon-multiagent"
main = "src/index.js"
compatibility_date = "2023-12-01"

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[d1_databases]]
binding = "DB"
database_name = "switchon_db"
database_id = "placeholder-db-id"
